guy/AddWidgetTab
digi-serve/ab_platform_web pull request #110
Opened 2022-07-29 06:40 UTC by guyyoo

2022-07-29 08:25 UTC, nh758 requested changes

2022-07-29 08:25 UTC, nh758 commented on AppBuilder/platform/views/ABViewTab.js
> +class TabPopup extends EventEmitter {
shouldn't this move to the designer? we won't use it anywhere else, right?

2022-07-29 08:25 UTC, nh758 commented on AppBuilder/platform/views/ABViewTab.js
> +   // constructor(values, application, parent, defaultValues) {
can wee delete instead of comment out? any reason to keep it here?

2022-07-29 08:28 UTC, wongpratan commented on AppBuilder/platform/views/viewComponent/ABViewTabComponent.js
> +               let selectedItem = baseView._viewComponents[0].view.id + "_menu";
ES6 string format

2022-07-29 08:28 UTC, wongpratan commented on AppBuilder/platform/views/viewComponent/ABViewTabComponent.js
> +               );
ES6 string format

2022-07-29 08:28 UTC, wongpratan commented on AppBuilder/platform/views/viewComponent/ABViewTabComponent.js
> +               "</span>"
*_*

2022-07-29 08:30 UTC, wongpratan approved these changes

2022-08-01 09:44 UTC, nh758 approved these changes

2022-08-01 09:45 UTC, merged