Migrate from v1
digi-serve/ab_platform_web pull request #19
Opened 2021-09-28 06:26 UTC by wongpratan

2021-10-04 05:26 UTC, Hiro-Nakamura requested changes

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewReportsManager.js
> +                        let dataCol = compInstance.AB.datacollections(
simplify to:
```
let dataCol = compInstance.AB.datacollectionByID(dcId) ;
```

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewReportsManager.js
> +                                       let sourceDc = compInstance.AB.datacollections(
`datacollectionByID(j.sid)`

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewReportsManager.js
> +                                       let targetDc = compInstance.AB.datacollections(
`datacollectionByID(ID) `

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewReportsManager.js
> +                                    let queryVal = JSON.parse(
safer to wrap `JSON.parse()`  in `try {} catch() {}` block.

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewReportsManager.js
> +            let datacollection = compInstance.AB.datacollections(
`datacollectionByID(ID) `

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewReportsManager.js
> +                                          reportRow[col] = new Date(
should use one of the `.toDate()` ,  `.toDateFormat()` or other ABFactory methods instead of referencing `moment` here directly.

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewTab.js
>                 App.AB.Dialog.Confirm({
you are remembering to change all these to `webix.confirm()`  right?

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewTab.js
> +                        '[webix_tm_id="' + ids.collapseMenu + '"]'
we could change all these to 
```
`[webix_tm_id="${ids.collapseMenu}"]`
```

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewProperties/ABViewPropertyEditPage.js
> +         formEdit: idBase + "_editForm",
```
`${idBase}_editForm`
```

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewProperties/ABViewPropertyLinkPage.js
> +         editPage: idBase + "_linkPage_editPage",
```
`${idBase}...`
```

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/workspaceViews/ABObjectWorkspaceViewGantt.js
> +            title: L("Title"),
move all these `labels.component.xxxx`  to directly reference `L("XXX")`

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/platform/workspaceViews/ABObjectWorkspaceViewKanban.js
> +            vGroup: L("Vertical Grouping"),
move away from the `labels.component.xxx`

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewRule.js
> +            action: L("Action"),
again, move away from `label.component.xxx`

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewRuleAction.js
> +            action: L("Action"),
same

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewRuleList.js
> +            header: L(this.childSettings.labels.header),
same

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionFormRecordRuleUpdateConnected.js
> +      this.labels.component.remoteCondition = L("How to choose which object:");
same: try to remove `this.labels.component.xxx` with direct references.

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionFormSubmitRuleConfirmMessage.js
>        var labels = (this.labels = {
same

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
>                 "*A value is required"
does this one need to be reduced too?

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
> +            setPlaceholder: L("Choose a field"),
same: make sure we are not going through a `label.component.xxx`

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
> +               AB.error(
`AB.notify.developer(err, {})`  here.

2021-10-04 05:26 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
> +                  AB.error(
`AB.notify.developer()`

2021-10-19 02:51 UTC, wongpratan commented on AppBuilder/platform/RowFilter.js
> +            case "not_in_data_collection": {
Just for set scope of `let` variable in `switch case` statement

2021-10-19 06:44 UTC, wongpratan commented on AppBuilder/platform/views/ABViewFormComponent.js
> +            field.settings.required == true ||
It might be better if it is able to support 
== 1

2021-11-10 10:12 UTC, Hiro-Nakamura requested changes
revamp the label usage and reference webix directly.

2021-11-10 10:12 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionFormSubmitRuleEmail.js
> +let L = (...params) => AB.Label()("", ...params);
change this

2021-11-10 10:12 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionFormSubmitRuleExistPage.js
> +let L = (...params) => AB.Label()("", ...params);
change this

2021-11-10 10:12 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionFormSubmitRuleWebsite.js
> +let L = (...params) => AB.Label()("", ...params);
change this

2021-11-10 10:12 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
> +let L = (...params) => AB.Label()("", ...params);
change this

2021-11-18 04:03 UTC, wongpratan commented on AppBuilder/platform/views/ABViewReportsManager.js
> +                                       bad(err);
Yes, it will be continue to work without filter conditions.

2021-11-18 04:06 UTC, wongpratan commented on AppBuilder/platform/views/ABViewReportsManager.js
> +                                 return webix.i18n.dateFormatStr(val);
`dateFormatStr` converts Date to string format.

2021-11-24 06:15 UTC, Hiro-Nakamura requested changes

2021-11-24 06:15 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewRuleList.js
> +            header: L(this.childSettings.labels.header),
should this be: this.childSettings.labels.headerDefault ??

2021-11-24 06:15 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionFormRecordRuleUpdateConnected.js
> +                  {}
include ```fieldID: this.selectedFieldID``` in the context data.

2021-11-24 06:15 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionFormRecordRuleUpdateConnected.js
> +                  {}
also, in the context data: note which Object:method() we are in.

2021-11-24 06:15 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
> +                  {},
use ```new Error("Could not find webix form")``` here so we can catch the stack trace.

2021-11-24 06:15 UTC, Hiro-Nakamura commented on AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
>                 .catch((err) => {
move ```.catch()``` handler to after the ```.then()```

2021-11-25 04:53 UTC, wongpratan commented on AppBuilder/platform/views/ABViewImage.js
> +            let url = `/file/upload/${currView.application.name}/${actionKey}/1`;
We have not keep .objectId and .fieldId data in this widget.
Should we change it now ? 
I think it will cause a compatible problem.

2021-11-30 06:54 UTC, Hiro-Nakamura requested changes

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldCombine.js
> +            labelWidth: this.AB.Config.labelWidthXLarge,
verify these configs ... I think I might have told you wrong on how to reference them

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldCombine.js
> +            labelWidth: this.AB.Config.labelWidthXLarge,
`AB.UISettings`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldConnect.js
> +   ABFieldConnectComponent.AB.objects().forEach((o) => {
Did you see this question?

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldConnect.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.UISettings`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldConnect.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.UISettings`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldConnect.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.UISettings`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldConnect.js
> +      // populate display text
Did you see this one?

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldUser.js
> +            labelWidth: this.AB.Config.labelWidthCheckbox,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldUser.js
> +            labelWidth: this.AB.Config.labelWidthCheckbox,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldUser.js
> +            labelWidth: this.AB.Config.labelWidthCheckbox,
`AB.Config.uiSettings().labelWidthCheckbox`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldUser.js
> +            labelWidth: this.AB.Config.labelWidthCheckbox,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldUser.js
> +            labelWidth: this.AB.Config.labelWidthCheckbox,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +               labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +                           width: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +                     labelWidth: this.AB.Config.labelWidthXLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCSVImporter.js
> +                     labelWidth: this.AB.Config.labelWidthXLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCarousel.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCarousel.js
> +                     labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCarousel.js
> +                     labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCarousel.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCarousel.js
> +                     labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewCarousel.js
> +                     labelWidth: this.AB.Config.labelWidthCheckbox,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewConditionalContainer.js
> +         AB
did you see this?

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewConditionalContainer.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewContainer.js
> +                  labelWidth: this.AB.Config.labelWidthXLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewDocxBuilder.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewGrid.js
> +            labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/ABViewTab.js
> +            labelWidth: this.AB.Config.labelWidthCheckbox,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewProperties/ABViewPropertyFilterData.js
> +               labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewProperties/ABViewPropertyFilterData.js
> +                           label: L('*need "LoadAll" from datasource'),
Don't include the "*" in the label anymore.

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewGridFilterMenu.js
> +                  labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewGridFilterMenu.js
> +                              label: L('*need "LoadAll" from datasource'),
no "*" in label

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewQueryBuilderObjectFieldConditions.js
> +            width: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-11-30 06:54 UTC, Hiro-Nakamura commented on AppBuilder/rules/ABViewRule.js
> +               labelWidth: this.AB.Config.labelWidthLarge,
`AB.Config.uiSettings()`

2021-12-22 08:27 UTC, wongpratan commented on AppBuilder/platform/views/ABViewGrid.js
> +               let toggleTab = (parentTab, wb) => {
It is ESlint reason.

https://github.com/digi-serve/ab_platform_web/blob/migrateFromV1/AppBuilder/platform/views/ABViewGrid.js#L858

2022-02-01 04:41 UTC, closed without merging