Refactor view ids.component
digi-serve/ab_platform_web pull request #229
Opened 2023-01-26 08:48 UTC by guyyoo

2023-02-06 04:03 UTC, nh758 approved these changes

2023-02-08 04:54 UTC, wongpratan approved these changes

2023-02-10 21:27 UTC, Hiro-Nakamura requested changes
Just a few things to look over ...

2023-02-10 21:27 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewComponent/ABViewReportsManagerComponent.js
> +      AB.componentId = AB.componentId || this.ids.component;
what's this for?

2023-02-10 21:27 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewComponent/ABViewTabComponent.js
>  const L = (...params) => AB.Multilingual.label(...params);
looks like we can get rid of the `L =` definition.

2023-02-10 21:27 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewComponent/ABViewTabComponent.js
> +               if ($tab?.hideProgress) $tab.hideProgress();
this should be `tab?.hideProgress?.();`

2023-02-10 21:27 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewComponent/ABViewTextComponent.js
>     async init(AB) {
doesn't look like we need this method.

2023-02-13 04:36 UTC, guyyoo commented on AppBuilder/platform/views/ABViewConditionalContainer.js
> +      await Promise.all(penddingSave);
Yes, It is working well.

2023-02-13 04:36 UTC, guyyoo commented on AppBuilder/platform/views/ABViewDetailSelectivity.js
> +   componentOld(App, idPrefix) {
Sure!

2023-02-13 05:48 UTC, guyyoo commented on AppBuilder/platform/views/viewComponent/ABViewCSVImporterComponent.js
> +      abWebix.ui(this.uiPopup());
I am just trying to use `this.AB.Webix` which is a local variable.

2023-02-13 05:54 UTC, guyyoo commented on AppBuilder/platform/views/viewComponent/ABViewCSVImporterComponent.js
> +            const linkFieldOptions = [];
Ok, I got it. I changed it back.

2023-02-13 06:10 UTC, guyyoo commented on AppBuilder/platform/views/viewComponent/ABViewConditionalContainerComponent.js
> +            $batch.showBatch("wait");
it's on `ui()`.

![Screenshot 2566-02-13 at 13 09 03](https://user-images.githubusercontent.com/80669791/218383532-55255662-851a-4756-b499-4bfa90bc6f54.png)

2023-02-13 07:33 UTC, guyyoo commented on AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
> +         if (image.settings.useHeight && image.settings.imageHeight > rowHeight)
I created `getSettings()` to get a copy of `field.settings`. Is that better? because here also has `useHeight` that is needed to access.

2023-02-13 22:31 UTC, Hiro-Nakamura requested changes
OK, that suggestion is my bad.  Let's not have the additional error message there.  After that, this is good to go.

2023-02-13 22:31 UTC, Hiro-Nakamura commented on AppBuilder/platform/views/viewComponent/ABViewCSVExporterComponent.js
> +            clientFilter.fieldsLoad(obj?.fields?.() ?? []);
OK, sorry to do this to you, but after I wrote that last question, I realized that the `dc.datasource` actually does some internal checking and will already post an error about not finding a proper obj to return.  So you don't actually have to add another one here too ...

2023-02-14 02:55 UTC, guyyoo commented
> OK, that suggestion is my bad. Let's not have the additional error message there. After that, this is good to go.

Ok, thank you.

2023-02-14 03:44 UTC, merged