refactor formio builder for v2
digi-serve/ab_platform_web pull request #249
Opened 2023-02-23 08:02 UTC by nh758

need to update route for image/file uploads

Should this move to the `ABDesigner`? We would only need this custom webix component for the Designer but all our other custom components live in platform web.

2023-02-23 18:48 UTC, Hiro-Nakamura requested changes

2023-02-23 18:48 UTC, Hiro-Nakamura commented on webix_custom_components/formioBuilder.js
> +    */
this doesn't seem to be the proper header for this function.

2023-02-23 18:48 UTC, Hiro-Nakamura commented on webix_custom_components/formioBuilder.js
> +            console.log(formComponents);
let's not leave `console.log()` statements in here.

2023-02-23 18:48 UTC, Hiro-Nakamura commented on webix_custom_components/formioBuilder.js
> +            this.builder = await Formio.builder(this.$view, formComponents, {
we should probably wrap this in a `try ... catch ...`

2023-02-23 18:48 UTC, Hiro-Nakamura commented on webix_custom_components/formioBuilder.js
> +      fields.forEach((entry) => {
so what are these `fields` here?  are they instances of an `ABField` objects?  or are they another kind of json definition?  (I don't see us using any method on them)

2023-02-23 18:53 UTC, Hiro-Nakamura commented
I agree, I think this code is only used in the ABDesigner, so we should move it there. 

The other custom components we define should be components we use in the normal operation of the AppBuilder.  But for things only used in the ABDesigner, we should move them there.

As for the routes, I keep thinking we should ask an `ABFieldFile` or `ABFieldImage` for it's route and use that there.  That way the routes always change if we update the `official` place for them.  But I'm not sure what we have available in this function at the time.  So we can keep it as is if we don't have access to them.

2023-02-24 02:11 UTC, nh758 commented
Thanks Johnny, I'll look moving this to the Designer and getting the route from the fields.

2023-02-24 19:04 UTC, Hiro-Nakamura approved these changes
lgtm

2023-02-24 19:04 UTC, Hiro-Nakamura commented on AppBuilder/platform/dataFields/ABFieldFile.js
> +                     text: "Tell a Developer to actually pay attention to this!",
I mean ... I'm thinking that at some point we actually need to pay attention to this.

2023-03-02 09:52 UTC, merged