Make Network Rest Great Again
digi-serve/ab_platform_web pull request #448
Opened 2024-02-03 00:03 UTC by Hiro-Nakamura

We had certain dependencies on the client of depending on the Socket Updates to properly update our local client data.  

however, this won't display the application correctly when we set out Network = "rest".  So these changes should enable a local client app to properly update itself without the input of socket updates.

## Release Notes

- [fix] have the client trigger local datacollection update handlers when we modify data.
- [fix] patch additional ABFieldUser quirks when working with values that need .id = .username
- [sync] with appropriate changes to core

2024-02-05 05:45 UTC, nh758 requested changes
One question below. Otherwise looks good, but again want to see our e2e test passing.

2024-02-05 05:45 UTC, nh758 commented on AppBuilder/platform/ABModel.js
> +   // if (model.AB.Network.type() != "socket") {
I don't understand this. Don't we still want this check?  Won't this cause duplicate updates when we use sockets?

2024-02-07 03:32 UTC, nh758 approved these changes
Looks good

2024-02-07 04:46 UTC, wongpratan approved these changes

2024-02-15 23:51 UTC, Hiro-Nakamura commented
How do I get this to kick off the KitchenSink e2e tests?

2024-03-04 23:27 UTC, merged