We need to pass forUpdate param otherwise the UUID of the connection …
digi-serve/ab_platform_web pull request #512
Opened 2024-05-02 08:42 UTC by jamesduncan

…is sent instead of the selected record's UUID

Related to this Issue:
https://github.com/digi-serve/ab_platform_web/issues/509

## Release Notes

- Fix a bug when updating M:1 records.

2024-05-02 17:59 UTC, Hiro-Nakamura approved these changes
LGTM

2024-05-02 17:59 UTC, Hiro-Nakamura commented
I wonder why our performance score dropped to 58 on this?

2024-05-02 18:04 UTC, Hiro-Nakamura requested changes
Actually, I would like to see better comments in the `ABFieldConnectCore`.`getRelationValue()` method so we actually understand what the `options.forUpdate` is for.  

Looks like we basically need to send that everytime we are using the `fn()` outside of a `Search` situation.

But this PR is good to go.

2024-05-03 08:06 UTC, wongpratan approved these changes

2024-05-09 03:49 UTC, merged